language: python
python: 3.3
env:
  - TOX_ENV=pypy-trunk
  - TOX_ENV=pypy-1.6.X
  - TOX_ENV=pypy-1.5.X
  - TOX_ENV=pypy-1.4.X
  - TOX_ENV=py33-trunk
  - TOX_ENV=py33-1.6.X
  - TOX_ENV=py33-1.5.X
  - TOX_ENV=py32-trunk
  - TOX_ENV=py32-1.6.X
  - TOX_ENV=py32-1.5.X
  - TOX_ENV=py27-trunk
  - TOX_ENV=py27-1.6.X
  - TOX_ENV=py27-1.5.X
  - TOX_ENV=py27-1.4.X
  - TOX_ENV=py26-1.6.X
  - TOX_ENV=py26-1.5.X
  - TOX_ENV=py26-1.4.X
install:
  - pip install coveralls
  - pip install tox
script:
  # https://github.com/travis-ci/travis-ci/issues/2218
  - export PATH=/opt/python/2.7.6/bin:/opt/python/2.6.9/bin:/opt/python/3.4.0/bin:/opt/python/3.3.5/bin:/opt/python/3.2.5/bin:/opt/python/pypy-2.2.1/bin:$PATH
  - tox -e $TOX_ENV
after_success: coveralls
